import { ToastContainer } from 'react-toastify';

import OrderModalAddress from '@/components/orderModalAddress/orderModalAddress';
import OrderModalCard from '@/components/orderModalCard/orderModalCard';
import HomeAnimation from '@/components/home-animation/HomeAnimation';
import ThemeProvider from '@/providers/ThemeProvider';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import ModalOrderCheckout from '@/components/modalOrderCheckout/modalOrderCheckout';
import AuthProvider from '@/providers/AuthProvider';

import 'react-toastify/dist/ReactToastify.css';
import 'normalize.css';
import './styles/index.css';

export const metadata = {
  title: {
    template: '%s | Sweet Dreams',
    default: 'Sweet Dreams',
  },
  description: 'Generated by create next app',
  icons: {
    rel: 'icon',
    icon: '/favicon.svg',
    type: 'image/svg+xml',
  },
};

export default function RootLayout({ children, session }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <AuthProvider>
          <body>
            <ToastContainer
              position="bottom-right"
              autoClose={5000}
              hideProgressBar={false}
              closeOnClick
              rtl={false}
              theme="light"
            />

            <div className="page">
              <Header />
              <main className="main">{children}</main>
              <Footer />
            </div>

            {/* <HomeAnimation /> */}
            <div id="modal-root">
              <ModalOrderCheckout>
                {/* <OrderModalCard /> */}
                <OrderModalAddress />
              </ModalOrderCheckout>
            </div>
          </body>
        </AuthProvider>
      </html>
    </ThemeProvider>
  );
}
