export const initialValues = {
  email: '',
  name: '',
  lastName: '',
  country: '',
  region: '',
  zip: '',
  city: '',
  street: '',
  building: '',
  unit: '',
  phone: '',
  card: '',
  date: '',
  security: '',
  cardName: '',
  isSaveInformation: false,
  isSaveAddress: false,
  isSavePayment: false,
};
